// Generated by npm run content:sync. Edit visitor-facing copy from /admin, not this file.
export const defaultCopy = [
  {
    "id": "c-1303p2r1v06svv",
    "group": "about",
    "source": "א.ס מיזוג אוויר מתמחה במכירת מזגנים ובשירותי התקנה, תחזוקה ותיקונים. אנחנו מלווים את הבחירה לבית ולעסק, ומתאימים את הפתרון לצרכים של החלל ושל האנשים שמשתמשים בו.",
    "he": "א.ס מיזוג אוויר מתמחה במכירת מזגנים ובשירותי התקנה, תחזוקה ותיקונים. אנחנו מלווים את הבחירה לבית ולעסק, ומתאימים את הפתרון לצרכים של החלל ושל האנשים שמשתמשים בו.",
    "ar": "شركة א.ס מיזוג אוויר متخصصة في بيع المكيفات وخدمات التركيب والصيانة والإصلاح. نرافق اختيارك للبيت والعمل، ونراعي احتياجات المساحة والأشخاص الذين يستخدمونها.",
    "en": "A.S Air Conditioning specialises in air conditioner sales, installation, maintenance and repairs. We guide choices for homes and businesses, with solutions shaped around the space and the people who use it."
  },
  {
    "id": "c-1km8rycjclscc",
    "group": "about",
    "source": "אודות א.ס",
    "he": "אודות א.ס",
    "ar": "عن א.ס",
    "en": "ABOUT A.S"
  },
  {
    "id": "c-1qq1n53ipn217",
    "group": "about",
    "source": "בואו נכיר",
    "he": "בואו נכיר",
    "ar": "لنتعرف عليك",
    "en": "Let’s get acquainted"
  },
  {
    "id": "c-cn4x4o194aeew",
    "group": "about",
    "source": "הדרך שלנו",
    "he": "הדרך שלנו",
    "ar": "طريقتنا",
    "en": "HOW WE WORK"
  },
  {
    "id": "c-ztknet1dpxf39",
    "group": "about",
    "source": "הפרטים הקטנים. ההבדל הגדול.",
    "he": "הפרטים הקטנים. ההבדל הגדול.",
    "ar": "تفاصيل صغيرة. فرق كبير.",
    "en": "Small details. A meaningful difference."
  },
  {
    "id": "c-1npnzom1bunpp2",
    "group": "about",
    "source": "יחס אישי לאורך הדרך.",
    "he": "יחס אישי לאורך הדרך.",
    "ar": "اهتمام شخصي بكل خطوة.",
    "en": "Personal care along the way."
  },
  {
    "id": "c-1esgatd1h90t11",
    "group": "about",
    "source": "מאחורי כל מערכת מיזוג יש אנשים שרוצים להרגיש בנוח. זו נקודת ההתחלה שלנו.",
    "he": "מאחורי כל מערכת מיזוג יש אנשים שרוצים להרגיש בנוח. זו נקודת ההתחלה שלנו.",
    "ar": "وراء كل نظام تكييف أناس يريدون الراحة. من هنا نبدأ.",
    "en": "Behind every air conditioning system are people who want to feel comfortable. That’s where we start."
  },
  {
    "id": "c-15uj7zfzg65f",
    "group": "about",
    "source": "מומחים למיזוג, עם מחשבה עליכם.",
    "he": "מומחים למיזוג, עם מחשבה עליכם.",
    "ar": "متخصصون في التكييف، نهتم براحتك.",
    "en": "Air conditioning expertise, with you in mind."
  },
  {
    "id": "c-1rtn25d1cbcj4p",
    "group": "about",
    "source": "מיזוג שמשתלב בבית",
    "he": "מיזוג שמשתלב בבית",
    "ar": "تكييف ينسجم مع البيت",
    "en": "Air conditioning that feels at home"
  },
  {
    "id": "c-1fyw3do1r13udc",
    "group": "about",
    "source": "עבורנו, שירות טוב הוא הסבר ברור, תיאום מראש ותשומת לב לפרטים. אנחנו נותנים שירות בכל ערי ישראל, בעברית ובערבית.",
    "he": "עבורנו, שירות טוב הוא הסבר ברור, תיאום מראש ותשומת לב לפרטים. אנחנו נותנים שירות בכל ערי ישראל, בעברית ובערבית.",
    "ar": "الخدمة الجيدة بالنسبة لنا تعني شرحًا واضحًا وتنسيقًا مسبقًا واهتمامًا بالتفاصيل. نخدم جميع المدن في إسرائيل بالعربية والعبرية.",
    "en": "To us, good service means clear explanations, arrangements made in advance and attention to detail. We serve every city in Israel, with personal service in Hebrew and Arabic."
  },
  {
    "id": "c-1tx1i2g11m15ko",
    "group": "about",
    "source": "פתרון מיזוג שלם.",
    "he": "פתרון מיזוג שלם.",
    "ar": "حل تكييف متكامل.",
    "en": "A complete air conditioning solution."
  },
  {
    "id": "c-stwf5ndup36j",
    "group": "contact",
    "source": "אזורי שירות",
    "he": "אזורי שירות",
    "ar": "مناطق الخدمة",
    "en": "Where we work"
  },
  {
    "id": "c-iqkitao1k8c2",
    "group": "contact",
    "source": "איך לפנות אליכם?",
    "he": "איך לפנות אליכם?",
    "ar": "كيف نناديك؟",
    "en": "How should we address you?"
  },
  {
    "id": "c-1jf52o2fur066",
    "group": "contact",
    "source": "אנחנו כאן בשבילכם.",
    "he": "אנחנו כאן בשבילכם.",
    "ar": "نحن هنا لمساعدتك.",
    "en": "Here to help."
  },
  {
    "id": "c-1qtnyrt1xyoen1",
    "group": "contact",
    "source": "בדיקת הבקשה",
    "he": "בדיקת הבקשה",
    "ar": "مراجعة الطلب",
    "en": "Review your request"
  },
  {
    "id": "c-yi5tsxsepbk1",
    "group": "contact",
    "source": "בואו נעשה לכם נעים.",
    "he": "בואו נעשה לכם נעים.",
    "ar": "لنجعل بيتك أكثر راحة.",
    "en": "Let’s make you comfortable."
  },
  {
    "id": "c-clwg7up1f8u2",
    "group": "contact",
    "source": "דגם שמעניין אתכם",
    "he": "דגם שמעניין אתכם",
    "ar": "الموديل الذي يهمك",
    "en": "Model you’re interested in"
  },
  {
    "id": "c-ea0tums5nd9m",
    "group": "contact",
    "source": "דוא״ל",
    "he": "דוא״ל",
    "ar": "البريد الإلكتروني",
    "en": "Email"
  },
  {
    "id": "c-ny0nyd1buvcrh",
    "group": "contact",
    "source": "הבקשה מוכנה לבדיקה",
    "he": "הבקשה מוכנה לבדיקה",
    "ar": "طلبك جاهز للمراجعة",
    "en": "Your request is ready to review"
  },
  {
    "id": "c-1a6ou62cgmery",
    "group": "contact",
    "source": "ההודעה לא נשלחה. שולחים מתוך וואטסאפ לאחר הבדיקה.",
    "he": "ההודעה לא נשלחה. שולחים מתוך וואטסאפ לאחר הבדיקה.",
    "ar": "لم يتم إرسال الرسالة. أرسلها من واتساب بعد المراجعة.",
    "en": "Nothing has been sent. Send the message in WhatsApp after reviewing it."
  },
  {
    "id": "c-1c1d2l61fvtjiy",
    "group": "contact",
    "source": "היכן נדרש השירות?",
    "he": "היכן נדרש השירות?",
    "ar": "أين تحتاج الخدمة؟",
    "en": "Where do you need us?"
  },
  {
    "id": "c-j5t9cdzlp01l",
    "group": "contact",
    "source": "הכינו בקשה מסודרת והמשיכו איתה לוואטסאפ.",
    "he": "הכינו בקשה מסודרת והמשיכו איתה לוואטסאפ.",
    "ar": "جهز طلبك ثم تابع به إلى واتساب.",
    "en": "Prepare your request, then continue with it to WhatsApp."
  },
  {
    "id": "c-1fkne671bm56gb",
    "group": "contact",
    "source": "הכנת הבקשה",
    "he": "הכנת הבקשה",
    "ar": "جهّز الطلب",
    "en": "Prepare my request"
  },
  {
    "id": "c-d9kshrl44py3",
    "group": "contact",
    "source": "הפרטים לא נשלחים ולא נשמרים באתר. תוכלו לבדוק את הבקשה לפני המשך לוואטסאפ ושליחתה.",
    "he": "הפרטים לא נשלחים ולא נשמרים באתר. תוכלו לבדוק את הבקשה לפני המשך לוואטסאפ ושליחתה.",
    "ar": "لا تُرسل البيانات ولا تُحفظ في الموقع. يمكنك مراجعة الطلب قبل المتابعة إلى واتساب وإرساله.",
    "en": "Your details are not sent or stored on this site. Review your request before continuing to WhatsApp and sending it."
  },
  {
    "id": "c-1oo3tutwtcrud",
    "group": "contact",
    "source": "טלפון",
    "he": "טלפון",
    "ar": "الهاتف",
    "en": "Call us"
  },
  {
    "id": "c-93g2gn1vwptcn",
    "group": "contact",
    "source": "טלפון: ",
    "he": "טלפון: ",
    "ar": "الهاتف: ",
    "en": "Phone: "
  },
  {
    "id": "c-kr32zv14wvtxf",
    "group": "contact",
    "source": "טרם בחרתי / לא רלוונטי",
    "he": "טרם בחרתי / לא רלוונטי",
    "ar": "لم أختر بعد / لا ينطبق",
    "en": "Not chosen yet / not applicable"
  },
  {
    "id": "c-an1nh47hpyx8",
    "group": "contact",
    "source": "ייעוץ ורכישת מזגן",
    "he": "ייעוץ ורכישת מזגן",
    "ar": "استشارة وشراء مكيف",
    "en": "Advice & a new air conditioner"
  },
  {
    "id": "c-1vx5vad1en6x0d",
    "group": "contact",
    "source": "יצירת קשר",
    "he": "יצירת קשר",
    "ar": "تواصل معنا",
    "en": "LET’S CONNECT"
  },
  {
    "id": "c-wvpkrb174k7ib",
    "group": "contact",
    "source": "יש לכם דגם או קוד תקלה? ציינו אותם בבקשה כדי שנוכל לעזור בצורה מדויקת יותר.",
    "he": "יש לכם דגם או קוד תקלה? ציינו אותם בבקשה כדי שנוכל לעזור בצורה מדויקת יותר.",
    "ar": "لديك موديل أو رمز عطل؟ اذكره لنساعدك بدقة أكبر.",
    "en": "Have a model name or an error code? Include it so we can help more precisely."
  },
  {
    "id": "c-1yad0huasvt06",
    "group": "contact",
    "source": "כמה פרטים, ומתחילים",
    "he": "כמה פרטים, ומתחילים",
    "ar": "بعض التفاصيل، ونبدأ",
    "en": "A FEW DETAILS TO START"
  },
  {
    "id": "c-ux20xzuw0tlz",
    "group": "contact",
    "source": "כתובת",
    "he": "כתובת",
    "ar": "العنوان",
    "en": "Address"
  },
  {
    "id": "c-b4o3xz11kyv2j",
    "group": "contact",
    "source": "להמשך בוואטסאפ",
    "he": "להמשך בוואטסאפ",
    "ar": "تابع عبر واتساب",
    "en": "Continue to WhatsApp"
  },
  {
    "id": "c-yipmku1osy9u2",
    "group": "contact",
    "source": "מדברים ישירות",
    "he": "מדברים ישירות",
    "ar": "تواصل مباشر",
    "en": "A REAL CONVERSATION"
  },
  {
    "id": "c-if68xs1a8943s",
    "group": "contact",
    "source": "מה נוכל לעשות בשבילכם?",
    "he": "מה נוכל לעשות בשבילכם?",
    "ar": "كيف يمكننا مساعدتك؟",
    "en": "How can we help?"
  },
  {
    "id": "c-dlw4tra6nhiv",
    "group": "contact",
    "source": "מספר טלפון",
    "he": "מספר טלפון",
    "ar": "رقم الهاتف",
    "en": "Phone number"
  },
  {
    "id": "c-15l7w1qdycuyu",
    "group": "contact",
    "source": "מספר טלפון עם 9–20 תווים",
    "he": "מספר טלפון עם 9–20 תווים",
    "ar": "رقم هاتف من 9 إلى 20 خانة",
    "en": "A phone number with 9–20 characters"
  },
  {
    "id": "c-19xq90s3t8cg0",
    "group": "contact",
    "source": "סוג הבקשה",
    "he": "סוג הבקשה",
    "ar": "نوع الطلب",
    "en": "What do you need?"
  },
  {
    "id": "c-1rgfcyh1f406eh",
    "group": "contact",
    "source": "סוג המזגן, קוד תקלה או פרטים על החלל…",
    "he": "סוג המזגן, קוד תקלה או פרטים על החלל…",
    "ar": "نوع المكيف أو رمز العطل أو تفاصيل المساحة…",
    "en": "Model, error code or a few details about your space…"
  },
  {
    "id": "c-km51v416aj7o0",
    "group": "contact",
    "source": "ספרו לנו קצת יותר",
    "he": "ספרו לנו קצת יותר",
    "ar": "أخبرنا بالمزيد",
    "en": "Tell us a little more"
  },
  {
    "id": "c-16qt4t9gqbx2x",
    "group": "contact",
    "source": "עיר",
    "he": "עיר",
    "ar": "المدينة",
    "en": "City"
  },
  {
    "id": "c-1n2zb7bfq7rdv",
    "group": "contact",
    "source": "עיר: ",
    "he": "עיר: ",
    "ar": "المدينة: ",
    "en": "City: "
  },
  {
    "id": "c-14hjrp4149v98w",
    "group": "contact",
    "source": "שאלה קטנה, מזגן חדש או תקלה שדורשת טיפול — נשמח לדבר, להבין ולעזור.",
    "he": "שאלה קטנה, מזגן חדש או תקלה שדורשת טיפול — נשמח לדבר, להבין ולעזור.",
    "ar": "سؤال، مكيف جديد أو عطل يحتاج إصلاحًا، يسعدنا أن نفهم احتياجك ونساعدك.",
    "en": "A quick question, a new air conditioner or a fault that needs attention — we’re here to listen and help."
  },
  {
    "id": "c-go54e1frpc1e",
    "group": "contact",
    "source": "שלום א.ס מיזוג אוויר, אשמח לתאם:",
    "he": "שלום א.ס מיזוג אוויר, אשמח לתאם:",
    "ar": "مرحبًا א.ס מיזוג אוויר، أريد طلب:",
    "en": "Hello A.S Air Conditioning, I’d like to request:"
  },
  {
    "id": "c-1han9qd1iq13gl",
    "group": "contact",
    "source": "שלחו לנו הודעה",
    "he": "שלחו לנו הודעה",
    "ar": "أرسل لنا رسالة",
    "en": "Start a conversation"
  },
  {
    "id": "c-1cdgul1ecgcgd",
    "group": "contact",
    "source": "שם מלא",
    "he": "שם מלא",
    "ar": "الاسم الكامل",
    "en": "Full name"
  },
  {
    "id": "c-kvjfku1l4nhia",
    "group": "contact",
    "source": "שם: ",
    "he": "שם: ",
    "ar": "الاسم: ",
    "en": "Name: "
  },
  {
    "id": "c-1e32q451bvgcn1",
    "group": "contact",
    "source": "שעות פעילות",
    "he": "שעות פעילות",
    "ar": "ساعات العمل",
    "en": "Business hours"
  },
  {
    "id": "c-pq18nw15le3ak",
    "group": "faq",
    "source": "טוב לדעת",
    "he": "טוב לדעת",
    "ar": "معلومات تفيدك",
    "en": "GOOD TO KNOW"
  },
  {
    "id": "c-1easn6owyxe5c",
    "group": "faq",
    "source": "לכל השאלות",
    "he": "לכל השאלות",
    "ar": "جميع الأسئلة",
    "en": "All questions"
  },
  {
    "id": "c-od85kh7wa765",
    "group": "faq",
    "source": "קצת ידע. הרבה שקט.",
    "he": "קצת ידע. הרבה שקט.",
    "ar": "معرفة أكثر. راحة أكبر.",
    "en": "A little clarity. A lot of comfort."
  },
  {
    "id": "c-13geqlh2xkpz1",
    "group": "faq",
    "source": "שאלות נפוצות",
    "he": "שאלות נפוצות",
    "ar": "أسئلة شائعة",
    "en": "FREQUENTLY ASKED QUESTIONS"
  },
  {
    "id": "c-1rnnftjmv5d6f",
    "group": "faq",
    "source": "שואלים. מבינים. בוחרים.",
    "he": "שואלים. מבינים. בוחרים.",
    "ar": "اسأل، افهم، واختر.",
    "en": "Good questions. Clear answers."
  },
  {
    "id": "c-w3525zazrwpn",
    "group": "faq",
    "source": "תשובות לשאלות על בחירת מזגן, התקנה ושירות.",
    "he": "תשובות לשאלות על בחירת מזגן, התקנה ושירות.",
    "ar": "إجابات حول اختيار المكيف والتركيب والصيانة.",
    "en": "Answers about choosing an air conditioner, installation and service."
  },
  {
    "id": "c-12z92hq141fmau",
    "group": "global",
    "source": "אוויר טוב מתחיל בשיחה.",
    "he": "אוויר טוב מתחיל בשיחה.",
    "ar": "هواء أفضل يبدأ بمحادثة.",
    "en": "Better air starts with a conversation."
  },
  {
    "id": "c-11bq6vvol4e6r",
    "group": "global",
    "source": "אינוורטר",
    "he": "אינוורטר",
    "ar": "إنفرتر",
    "en": "INVERTER"
  },
  {
    "id": "c-1baq5yp162xfex",
    "group": "global",
    "source": "אפשר גם בוואטסאפ",
    "he": "אפשר גם בוואטסאפ",
    "ar": "تواصل أيضًا عبر واتساب",
    "en": "Or chat on WhatsApp"
  },
  {
    "id": "c-12qkrql1iu773h",
    "group": "global",
    "source": "בואו למצוא את הנוחות שלכם",
    "he": "בואו למצוא את הנוחות שלכם",
    "ar": "اكتشف راحتك",
    "en": "Find your comfort"
  },
  {
    "id": "c-k1qkci19oah3e",
    "group": "global",
    "source": "בואו נדבר",
    "he": "בואו נדבר",
    "ar": "لنتحدث",
    "en": "Let’s talk"
  },
  {
    "id": "c-18yg08wd63448",
    "group": "global",
    "source": "בואו נדבר על נוחות",
    "he": "בואו נדבר על נוחות",
    "ar": "لنتحدث عن راحتك",
    "en": "LET’S TALK COMFORT"
  },
  {
    "id": "c-1qgkf6o1cts6m8",
    "group": "global",
    "source": "בית",
    "he": "בית",
    "ar": "الرئيسية",
    "en": "Home"
  },
  {
    "id": "c-10hv11m158y8xq",
    "group": "global",
    "source": "דברו איתנו בוואטסאפ",
    "he": "דברו איתנו בוואטסאפ",
    "ar": "تواصل عبر واتساب",
    "en": "Chat with us on WhatsApp"
  },
  {
    "id": "c-mfda0d1t60dg1",
    "group": "global",
    "source": "דילוג לתוכן",
    "he": "דילוג לתוכן",
    "ar": "انتقل إلى المحتوى",
    "en": "Skip to content"
  },
  {
    "id": "c-1hji73p1jjfyeh",
    "group": "global",
    "source": "השוואה",
    "he": "השוואה",
    "ar": "قارن",
    "en": "Compare"
  },
  {
    "id": "c-gczdpulhhw2m",
    "group": "global",
    "source": "חדר שינה",
    "he": "חדר שינה",
    "ar": "غرفة النوم",
    "en": "Bedroom"
  },
  {
    "id": "c-aep9ofj91j3v",
    "group": "global",
    "source": "חלל גדול",
    "he": "חלל גדול",
    "ar": "مساحة كبيرة",
    "en": "Large space"
  },
  {
    "id": "c-d5drfaicbqfy",
    "group": "global",
    "source": "חלל משפחתי",
    "he": "חלל משפחתי",
    "ar": "مساحة عائلية",
    "en": "Living space"
  },
  {
    "id": "c-esyqcooriprw",
    "group": "global",
    "source": "לא זמין כרגע",
    "he": "לא זמין כרגע",
    "ar": "غير متوفر حاليًا",
    "en": "Currently unavailable"
  },
  {
    "id": "c-neinfizy07a2",
    "group": "global",
    "source": "מזגן חדש או טיפול בקיים? אנחנו כאן בשבילכם.",
    "he": "מזגן חדש או טיפול בקיים? אנחנו כאן בשבילכם.",
    "ar": "مكيف جديد أو صيانة لمكيفك؟ نحن هنا لمساعدتك.",
    "en": "A new air conditioner or care for your current one? We’re here to help."
  },
  {
    "id": "c-ns7h6cq8o7s",
    "group": "global",
    "source": "מחיר",
    "he": "מחיר",
    "ar": "السعر",
    "en": "Price"
  },
  {
    "id": "c-15qvu1y1qyycse",
    "group": "global",
    "source": "מחיר להמחשה",
    "he": "מחיר להמחשה",
    "ar": "سعر توضيحي",
    "en": "Indicative price"
  },
  {
    "id": "c-kwsiuk1kdjv0s",
    "group": "global",
    "source": "מיקום באתר",
    "he": "מיקום באתר",
    "ar": "مسار الصفحة",
    "en": "Breadcrumb"
  },
  {
    "id": "c-1401zj41suh12o",
    "group": "global",
    "source": "מכירה, התקנה, תחזוקה ותיקונים.",
    "he": "מכירה, התקנה, תחזוקה ותיקונים.",
    "ar": "بيع وتركيب وصيانة وإصلاح.",
    "en": "Sales, installation, maintenance and repairs."
  },
  {
    "id": "c-l3rc9834yse8",
    "group": "global",
    "source": "מכניסים הביתה אוויר טוב.",
    "he": "מכניסים הביתה אוויר טוב.",
    "ar": "هواء أفضل، وراحة لبيتك.",
    "en": "Better air, brought home."
  },
  {
    "id": "c-1nklfkdiehiyl",
    "group": "global",
    "source": "נשמח לשמוע מכם",
    "he": "נשמח לשמוע מכם",
    "ar": "يسعدنا تواصلك",
    "en": "Get in touch"
  },
  {
    "id": "c-1r0zwqo1va5gcw",
    "group": "global",
    "source": "פרטים והתאמה",
    "he": "פרטים והתאמה",
    "ar": "التفاصيل والاختيار",
    "en": "Explore model"
  },
  {
    "id": "c-v93kjxy810g9",
    "group": "global",
    "source": "פתיחת תפריט",
    "he": "פתיחת תפריט",
    "ar": "فتح القائمة",
    "en": "Toggle navigation"
  },
  {
    "id": "c-resmhn176oq93",
    "group": "global",
    "source": "רכישה, משלוח ואחריות",
    "he": "רכישה, משלוח ואחריות",
    "ar": "الشراء والتوصيل والضمان",
    "en": "Purchase, delivery & warranty"
  },
  {
    "id": "c-nicody915l1m",
    "group": "global",
    "source": "שאלות נפוצות",
    "he": "שאלות נפוצות",
    "ar": "أسئلة شائعة",
    "en": "Frequently asked questions"
  },
  {
    "id": "c-1ft9sg9buk4m1",
    "group": "global",
    "source": "שפת האתר",
    "he": "שפת האתר",
    "ar": "لغة الموقع",
    "en": "Website language"
  },
  {
    "id": "c-tw9y7n126ndnb",
    "group": "global",
    "source": "תפריט ראשי",
    "he": "תפריט ראשי",
    "ar": "القائمة الرئيسية",
    "en": "Main navigation"
  },
  {
    "id": "c-1fzskuj1dgj6i3",
    "group": "home",
    "source": "אני צריך שירות למזגן",
    "he": "אני צריך שירות למזגן",
    "ar": "أحتاج صيانة للمكيف",
    "en": "Book a service"
  },
  {
    "id": "c-13kqk2ccyn8fo",
    "group": "home",
    "source": "בדיוק כמו שאתם אוהבים",
    "he": "בדיוק כמו שאתם אוהבים",
    "ar": "تمامًا كما تحب",
    "en": "Just the way you like it"
  },
  {
    "id": "c-3htlfr1qk2ywb",
    "group": "home",
    "source": "בחירה בראש שקט",
    "he": "בחירה בראש שקט",
    "ar": "اختيار بكل ثقة",
    "en": "Choose with confidence"
  },
  {
    "id": "c-1bzm25e3osi1i",
    "group": "home",
    "source": "בחירה לפי החלל",
    "he": "בחירה לפי החלל",
    "ar": "اختيار حسب مساحتك",
    "en": "YOUR SPACE. YOUR COMFORT."
  },
  {
    "id": "c-1hws20x12lzit1",
    "group": "home",
    "source": "בכל עונה / 01",
    "he": "בכל עונה / 01",
    "ar": "في كل موسم / 01",
    "en": "01 / EVERY SEASON"
  },
  {
    "id": "c-p8kzza1u40vwu",
    "group": "home",
    "source": "האוויר הנכון.",
    "he": "האוויר הנכון.",
    "ar": "الهواء المناسب.",
    "en": "Better air."
  },
  {
    "id": "c-ar7i1m1u9q2hm",
    "group": "home",
    "source": "האוויר משתנה.",
    "he": "האוויר משתנה.",
    "ar": "الهواء يتغير.",
    "en": "Seasons change."
  },
  {
    "id": "c-d3yngk14qey68",
    "group": "home",
    "source": "הבית שלכם.",
    "he": "הבית שלכם.",
    "ar": "لبيتك.",
    "en": "Your home."
  },
  {
    "id": "c-11zkh3e186jweq",
    "group": "home",
    "source": "החליקו כדי לגלות עוד דגמים",
    "he": "החליקו כדי לגלות עוד דגמים",
    "ar": "اسحب لاكتشاف موديلات أخرى",
    "en": "Swipe to explore more models"
  },
  {
    "id": "c-1q7iajw7mdgc0",
    "group": "home",
    "source": "המזגנים שלנו",
    "he": "המזגנים שלנו",
    "ar": "مكيفاتنا",
    "en": "OUR COLLECTION"
  },
  {
    "id": "c-b3yaslbv6h19",
    "group": "home",
    "source": "השירות נשאר.",
    "he": "השירות נשאר.",
    "ar": "خدمتنا ترافقك.",
    "en": "Our care stays."
  },
  {
    "id": "c-1qvuvi1l1o879",
    "group": "home",
    "source": "התאמה אישית",
    "he": "התאמה אישית",
    "ar": "اختيار يناسبك",
    "en": "Personal advice"
  },
  {
    "id": "c-su1vet17unzwd",
    "group": "home",
    "source": "התקנה מקצועית",
    "he": "התקנה מקצועית",
    "ar": "تركيب احترافي",
    "en": "Expert installation"
  },
  {
    "id": "c-cbxbp11nle12l",
    "group": "home",
    "source": "חושבים גם על החשמל",
    "he": "חושבים גם על החשמל",
    "ar": "نراعي استهلاك الطاقة",
    "en": "Mindful of energy"
  },
  {
    "id": "c-1dcgzlf1ibs5t3",
    "group": "home",
    "source": "טכנולוגיית אינוורטר חכמה",
    "he": "טכנולוגיית אינוורטר חכמה",
    "ar": "تقنية إنفرتر ذكية",
    "en": "Smart inverter technology"
  },
  {
    "id": "c-3y2tr931lp19",
    "group": "home",
    "source": "יותר ממזגן",
    "he": "יותר ממזגן",
    "ar": "أكثر من مجرد مكيف",
    "en": "BEYOND THE AIR CONDITIONER"
  },
  {
    "id": "c-6fxwxg1bv2au0",
    "group": "home",
    "source": "ייעוץ ברור, בלי סימני שאלה",
    "he": "ייעוץ ברור, בלי סימני שאלה",
    "ar": "استشارة واضحة، دون حيرة",
    "en": "Clear, personal guidance"
  },
  {
    "id": "c-rnfqdg9340r8",
    "group": "home",
    "source": "לגלות את הדגמים",
    "he": "לגלות את הדגמים",
    "ar": "اكتشف الموديلات",
    "en": "Discover the models"
  },
  {
    "id": "c-jbxvxq16krdu2",
    "group": "home",
    "source": "ליווי גם אחרי הרכישה",
    "he": "ליווי גם אחרי הרכישה",
    "ar": "متابعة بعد الشراء",
    "en": "After-sales support"
  },
  {
    "id": "c-tqxd6am1vs1a",
    "group": "home",
    "source": "לכל חדר, האוויר שלו.",
    "he": "לכל חדר, האוויר שלו.",
    "ar": "لكل غرفة، راحتها.",
    "en": "Every room has its own rhythm."
  },
  {
    "id": "c-rbczhwb12fkc",
    "group": "home",
    "source": "לכל שירותי המיזוג",
    "he": "לכל שירותי המיזוג",
    "ar": "اكتشف خدماتنا",
    "en": "Explore our services"
  },
  {
    "id": "c-egnhae1e7hdje",
    "group": "home",
    "source": "למציאת המזגן שלכם",
    "he": "למציאת המזגן שלכם",
    "ar": "اكتشف المكيف المناسب",
    "en": "Find your air conditioner"
  },
  {
    "id": "c-vw7v8wlewr50",
    "group": "home",
    "source": "מהבחירה ועד ההתקנה",
    "he": "מהבחירה ועד ההתקנה",
    "ar": "من الاختيار إلى التركيب",
    "en": "From choice to installation"
  },
  {
    "id": "c-4v1zovzxv0v",
    "group": "home",
    "source": "מההתקנה הראשונה ועד לתחזוקה השוטפת, אנחנו כאן כדי שהמזגן שלכם יעבוד כמו שצריך. פתרונות מקצועיים לבית ולעסק, בכל הארץ.",
    "he": "מההתקנה הראשונה ועד לתחזוקה השוטפת, אנחנו כאן כדי שהמזגן שלכם יעבוד כמו שצריך. פתרונות מקצועיים לבית ולעסק, בכל הארץ.",
    "ar": "من أول تركيب إلى الصيانة الدورية، نعتني بمكيفك ليعمل كما يجب. حلول احترافية للبيوت والأعمال في جميع المدن.",
    "en": "From the first installation to regular maintenance, we’re here to keep your air conditioner working well. Professional solutions for homes and businesses throughout Israel."
  },
  {
    "id": "c-1bolzg218met6q",
    "group": "home",
    "source": "מזגן טוב הוא רק ההתחלה. אנחנו כאן כדי להתאים, להתקין ולדאוג לנוחות שלכם — בקיץ, בחורף וכל מה שביניהם.",
    "he": "מזגן טוב הוא רק ההתחלה. אנחנו כאן כדי להתאים, להתקין ולדאוג לנוחות שלכם — בקיץ, בחורף וכל מה שביניהם.",
    "ar": "المكيف الجيد هو البداية. نساعدك في الاختيار والتركيب والصيانة، لراحة بيتك صيفًا وشتاءً.",
    "en": "A good air conditioner is just the beginning. We help you choose, install and enjoy lasting comfort — summer, winter and every day in between."
  },
  {
    "id": "c-1uvgwq615esabq",
    "group": "home",
    "source": "נוחות מתחילה בבחירה נכונה",
    "he": "נוחות מתחילה בבחירה נכונה",
    "ar": "الراحة تبدأ بالاختيار الصحيح",
    "en": "Great comfort. The right choice."
  },
  {
    "id": "c-3kiv1x15ob2ap",
    "group": "home",
    "source": "נוחות שמרגישים. איכות שסומכים עליה.",
    "he": "נוחות שמרגישים. איכות שסומכים עליה.",
    "ar": "راحة تشعر بها. جودة تثق بها.",
    "en": "Comfort you feel. Quality you trust."
  },
  {
    "id": "c-uqkq7dmunrat",
    "group": "home",
    "source": "נוחות, בכל פרט",
    "he": "נוחות, בכל פרט",
    "ar": "راحة في كل تفصيل",
    "en": "COMFORT, BY DESIGN."
  },
  {
    "id": "c-1oi55bzk9oyzn",
    "group": "home",
    "source": "סלון מואר ונעים עם מזגן עילי",
    "he": "סלון מואר ונעים עם מזגן עילי",
    "ar": "غرفة معيشة مضيئة ومريحة مع مكيف جداري",
    "en": "Bright, comfortable living room with a wall-mounted air conditioner"
  },
  {
    "id": "c-18q79zguzls5k",
    "group": "home",
    "source": "פתרון שלם במקום אחד",
    "he": "פתרון שלם במקום אחד",
    "ar": "حل متكامل في مكان واحد",
    "en": "A complete solution"
  },
  {
    "id": "c-1siuumk1g87jk",
    "group": "home",
    "source": "שירות אישי בעברית ובערבית",
    "he": "שירות אישי בעברית ובערבית",
    "ar": "خدمة بالعربية والعبرية",
    "en": "Service in Hebrew & Arabic"
  },
  {
    "id": "c-1d6aso4e974eg",
    "group": "home",
    "source": "של נוחות",
    "he": "של נוחות",
    "ar": "من الراحة",
    "en": "of comfort"
  },
  {
    "id": "c-u4fqb2sjzram",
    "group": "home",
    "source": "תמיד יש עם מי לדבר",
    "he": "תמיד יש עם מי לדבר",
    "ar": "دائمًا هناك من يساعدك",
    "en": "A real person to help"
  },
  {
    "id": "c-da12ed6snjvd",
    "group": "policies",
    "source": "בירור פרטים נוספים",
    "he": "בירור פרטים נוספים",
    "ar": "استفسر عن التفاصيل",
    "en": "Ask us for more details"
  },
  {
    "id": "c-i8pef05m1js",
    "group": "policies",
    "source": "כל הפרטים, בשקיפות.",
    "he": "כל הפרטים, בשקיפות.",
    "ar": "كل التفاصيل، بوضوح.",
    "en": "The details, clearly explained."
  },
  {
    "id": "c-1kxinfqpo71ay",
    "group": "policies",
    "source": "לפני שמחליטים, מוודאים יחד מה כלול בהצעה ומה מתאים לכם.",
    "he": "לפני שמחליטים, מוודאים יחד מה כלול בהצעה ומה מתאים לכם.",
    "ar": "قبل اتخاذ القرار نوضح ما يشمله العرض وما يناسبك.",
    "en": "Before you decide, we’ll clarify what’s included and what works for you."
  },
  {
    "id": "c-1oc64iivtbl2e",
    "group": "policies",
    "source": "רכישה ושירות",
    "he": "רכישה ושירות",
    "ar": "الشراء والخدمة",
    "en": "PURCHASE & SERVICE"
  },
  {
    "id": "c-g6hhp2o0sxr6",
    "group": "products",
    "source": "איפוס סינון",
    "he": "איפוס סינון",
    "ar": "إعادة ضبط الفلاتر",
    "en": "Reset filters"
  },
  {
    "id": "c-1987tpbrdgm0z",
    "group": "products",
    "source": "אפשר להשוות עד שלושה מזגנים. הסירו דגם כדי להוסיף אחר.",
    "he": "אפשר להשוות עד שלושה מזגנים. הסירו דגם כדי להוסיף אחר.",
    "ar": "يمكن مقارنة ثلاثة مكيفات كحد أقصى. أزل واحدًا لإضافة آخر.",
    "en": "Compare up to three models. Remove one to add another."
  },
  {
    "id": "c-1l2o8x710gz3jz",
    "group": "products",
    "source": "בחירה לפי חלל",
    "he": "בחירה לפי חלל",
    "ar": "الاختيار حسب المساحة",
    "en": "Filter by space"
  },
  {
    "id": "c-17tfgc81pmlpw8",
    "group": "products",
    "source": "בחרו 2–3 דגמים להשוואה",
    "he": "בחרו 2–3 דגמים להשוואה",
    "ar": "اختر 2–3 موديلات للمقارنة",
    "en": "Choose 2–3 models to compare"
  },
  {
    "id": "c-1fzko6b1q73w2z",
    "group": "products",
    "source": "בקשת הצעת מחיר",
    "he": "בקשת הצעת מחיר",
    "ar": "اطلب عرض سعر",
    "en": "Request a quote"
  },
  {
    "id": "c-yeovfl4v1bal",
    "group": "products",
    "source": "דגם",
    "he": "דגם",
    "ar": "الموديل",
    "en": "Model"
  },
  {
    "id": "c-1idfmmc1a2lj5s",
    "group": "products",
    "source": "דירוג אנרגטי",
    "he": "דירוג אנרגטי",
    "ar": "تصنيف الطاقة",
    "en": "Energy rating"
  },
  {
    "id": "c-1xp53hxhxzcvp",
    "group": "products",
    "source": "דירוג אנרגטי בקירור",
    "he": "דירוג אנרגטי בקירור",
    "ar": "تصنيف الطاقة للتبريد",
    "en": "Cooling energy rating"
  },
  {
    "id": "c-f40h31157ukq1",
    "group": "products",
    "source": "הדגם לא זמין",
    "he": "הדגם לא זמין",
    "ar": "الموديل غير متاح",
    "en": "This model is unavailable"
  },
  {
    "id": "c-1aglxth1gmhhvx",
    "group": "products",
    "source": "ההבדלים שעושים את הבחירה",
    "he": "ההבדלים שעושים את הבחירה",
    "ar": "تفاصيل تساعدك على الاختيار",
    "en": "The details that make the difference"
  },
  {
    "id": "c-12hi37cw3efos",
    "group": "products",
    "source": "המזגן",
    "he": "המזגן",
    "ar": "المكيف",
    "en": "The model"
  },
  {
    "id": "c-dv47ux1u0tfot",
    "group": "products",
    "source": "המזגנים שלנו",
    "he": "המזגנים שלנו",
    "ar": "المكيفات",
    "en": "Air conditioners"
  },
  {
    "id": "c-1hxxl0f1ds0ftj",
    "group": "products",
    "source": "הסרת",
    "he": "הסרת",
    "ar": "إزالة",
    "en": "Remove"
  },
  {
    "id": "c-1eyh0zy1uz0mam",
    "group": "products",
    "source": "הצגת כל הדגמים",
    "he": "הצגת כל הדגמים",
    "ar": "اعرض جميع الموديلات",
    "en": "Show all models"
  },
  {
    "id": "c-4r9l6d1ynllzp",
    "group": "products",
    "source": "הקטלוג",
    "he": "הקטלוג",
    "ar": "الكتالوج",
    "en": "THE COLLECTION"
  },
  {
    "id": "c-pdu4hh17uyhgt",
    "group": "products",
    "source": "השוו דגמים, הכירו את היתרונות ומצאו את הכיוון הנכון לבית שלכם. את הפרטים האחרונים נסגור יחד.",
    "he": "השוו דגמים, הכירו את היתרונות ומצאו את הכיוון הנכון לבית שלכם. את הפרטים האחרונים נסגור יחד.",
    "ar": "قارن الموديلات واكتشف مزاياها واختر الأنسب لبيتك. نساعدك في إتمام الاختيار.",
    "en": "Explore the models, compare the details and find your fit. We’ll help with the final choice."
  },
  {
    "id": "c-sz6iq61ll5cv6",
    "group": "products",
    "source": "השוואת דגמים",
    "he": "השוואת דגמים",
    "ar": "قارن الموديلات",
    "en": "Compare models"
  },
  {
    "id": "c-tzkaquio8xum",
    "group": "products",
    "source": "השראה לבית",
    "he": "השראה לבית",
    "ar": "إلهام لبيتك",
    "en": "ROOM INSPIRATION"
  },
  {
    "id": "c-1g1b443yiv34v",
    "group": "products",
    "source": "השראה לחלל",
    "he": "השראה לחלל",
    "ar": "إلهام للمساحة",
    "en": "Room inspiration"
  },
  {
    "id": "c-192egto161fkbs",
    "group": "products",
    "source": "התייעצות על הדגם",
    "he": "התייעצות על הדגם",
    "ar": "استشارة حول الموديل",
    "en": "Ask about this model"
  },
  {
    "id": "c-d8tbsc1omgrsk",
    "group": "products",
    "source": "התקנה ואחריות",
    "he": "התקנה ואחריות",
    "ar": "التركيب والضمان",
    "en": "Installation & warranty"
  },
  {
    "id": "c-1e3rpfz17pgu7z",
    "group": "products",
    "source": "התקנה והובלה יתומחרו בנפרד לפי הצורך. מחיר סופי ותנאי אחריות יפורטו בהצעה.",
    "he": "התקנה והובלה יתומחרו בנפרד לפי הצורך. מחיר סופי ותנאי אחריות יפורטו בהצעה.",
    "ar": "يُحدد التوصيل والتركيب حسب الحاجة. السعر النهائي وشروط الضمان ضمن عرض السعر.",
    "en": "Installation and delivery are quoted as needed. Final pricing and warranty terms are included in your quote."
  },
  {
    "id": "c-15ujps91av72r5",
    "group": "products",
    "source": "זמינות: בבירור מול החברה",
    "he": "זמינות: בבירור מול החברה",
    "ar": "التوفر: يُؤكد مع الشركة",
    "en": "Availability: confirm with us"
  },
  {
    "id": "c-2u846zq1bhov",
    "group": "products",
    "source": "חיפוש דגם",
    "he": "חיפוש דגם",
    "ar": "ابحث عن موديل",
    "en": "Search models"
  },
  {
    "id": "c-p5zhgvdbxq13",
    "group": "products",
    "source": "חלל מוצע",
    "he": "חלל מוצע",
    "ar": "المساحة المقترحة",
    "en": "Suggested space"
  },
  {
    "id": "c-j3pa9x1c7kuap",
    "group": "products",
    "source": "טכנולוגיה",
    "he": "טכנולוגיה",
    "ar": "التقنية",
    "en": "Technology"
  },
  {
    "id": "c-1rcxo7c1pfy7ko",
    "group": "products",
    "source": "יתרונות הדגם",
    "he": "יתרונות הדגם",
    "ar": "مزايا الموديل",
    "en": "Model features"
  },
  {
    "id": "c-1jeu85t1lj1dux",
    "group": "products",
    "source": "כל המותגים",
    "he": "כל המותגים",
    "ar": "جميع العلامات",
    "en": "All brands"
  },
  {
    "id": "c-1lqom15pmiqlx",
    "group": "products",
    "source": "כל המזגנים",
    "he": "כל המזגנים",
    "ar": "كل المكيفات",
    "en": "All models"
  },
  {
    "id": "c-1mpdxnj1qhct0n",
    "group": "products",
    "source": "כל הקטגוריות",
    "he": "כל הקטגוריות",
    "ar": "جميع التصنيفات",
    "en": "All categories"
  },
  {
    "id": "c-g7awz9zguflp",
    "group": "products",
    "source": "לא בטוחים במה לבחור?",
    "he": "לא בטוחים במה לבחור?",
    "ar": "تحتاج مساعدة في الاختيار؟",
    "en": "Need a little guidance?"
  },
  {
    "id": "c-4ld1l710ry8j3",
    "group": "products",
    "source": "לא נמצאו דגמים מתאימים",
    "he": "לא נמצאו דגמים מתאימים",
    "ar": "لا توجد موديلات مطابقة",
    "en": "No matching models"
  },
  {
    "id": "c-1sq2bmf15ulw97",
    "group": "products",
    "source": "לדייק את הבחירה",
    "he": "לדייק את הבחירה",
    "ar": "خصص اختيارك",
    "en": "Refine your choice"
  },
  {
    "id": "c-8kaj4ttzch59",
    "group": "products",
    "source": "לייעוץ אישי",
    "he": "לייעוץ אישי",
    "ar": "استشارة شخصية",
    "en": "Let’s find your fit"
  },
  {
    "id": "c-s0st49qwyugd",
    "group": "products",
    "source": "לכל המזגנים",
    "he": "לכל המזגנים",
    "ar": "جميع المكيفات",
    "en": "Explore all models"
  },
  {
    "id": "c-96b5uu1xpk7ju",
    "group": "products",
    "source": "למפרט המלא באתר היצרן",
    "he": "למפרט המלא באתר היצרן",
    "ar": "المواصفات الكاملة لدى المصنع",
    "en": "Full specifications from the manufacturer"
  },
  {
    "id": "c-17unrnz1vqyb9v",
    "group": "products",
    "source": "לפרטים",
    "he": "לפרטים",
    "ar": "التفاصيل",
    "en": "View model"
  },
  {
    "id": "c-1fk6lmr1sm3ptz",
    "group": "products",
    "source": "לשירותי ההתקנה שלנו",
    "he": "לשירותי ההתקנה שלנו",
    "ar": "خدمات التركيب",
    "en": "Our installation service"
  },
  {
    "id": "c-famjxc5hlsj8",
    "group": "products",
    "source": "מותג",
    "he": "מותג",
    "ar": "العلامة التجارية",
    "en": "Brand"
  },
  {
    "id": "c-n51l2bnixiub",
    "group": "products",
    "source": "מזגן עילי • אינוורטר",
    "he": "מזגן עילי • אינוורטר",
    "ar": "مكيف جداري • إنفرتر",
    "en": "WALL-MOUNTED • INVERTER"
  },
  {
    "id": "c-1qknarm1458qbq",
    "group": "products",
    "source": "מזגן שמתאים לצרכים שלכם.",
    "he": "מזגן שמתאים לצרכים שלכם.",
    "ar": "مكيف يناسب احتياجك.",
    "en": "Air conditioning that fits your needs."
  },
  {
    "id": "c-mfp2hj1dlmtvn",
    "group": "products",
    "source": "מזגנים",
    "he": "מזגנים",
    "ar": "مكيفات",
    "en": "models"
  },
  {
    "id": "c-12fj1leamatai",
    "group": "products",
    "source": "מחיר להמחשה",
    "he": "מחיר להמחשה",
    "ar": "السعر التوضيحي",
    "en": "Illustrative price"
  },
  {
    "id": "c-1czha59vitf2d",
    "group": "products",
    "source": "מחיר להמחשה בלבד",
    "he": "מחיר להמחשה בלבד",
    "ar": "سعر توضيحي فقط",
    "en": "Indicative price only"
  },
  {
    "id": "c-rgjhkedjfdv2",
    "group": "products",
    "source": "מחיר: מהגבוה לנמוך",
    "he": "מחיר: מהגבוה לנמוך",
    "ar": "السعر: من الأعلى للأقل",
    "en": "Price: high to low"
  },
  {
    "id": "c-qoupcumr47om",
    "group": "products",
    "source": "מחיר: מהנמוך לגבוה",
    "he": "מחיר: מהנמוך לגבוה",
    "ar": "السعر: من الأقل للأعلى",
    "en": "Price: low to high"
  },
  {
    "id": "c-kyko2t54u2b5",
    "group": "products",
    "source": "מחירים להמחשת הקטלוג בלבד. מחיר סופי, זמינות, הובלה והתקנה יאושרו בהצעת מחיר אישית. התאמה לחלל מחייבת ייעוץ.",
    "he": "מחירים להמחשת הקטלוג בלבד. מחיר סופי, זמינות, הובלה והתקנה יאושרו בהצעת מחיר אישית. התאמה לחלל מחייבת ייעוץ.",
    "ar": "الأسعار لتوضيح الكتالوج فقط. يُؤكد السعر النهائي والتوفر والتوصيل والتركيب بعرض سعر شخصي. اختيار القدرة يتطلب استشارة.",
    "en": "Prices are for catalog demonstration. Final pricing, availability, delivery and installation are confirmed in a personal quote. Space suitability requires consultation."
  },
  {
    "id": "c-1sg0rrd5q9b1",
    "group": "products",
    "source": "מידע על הדגם",
    "he": "מידע על הדגם",
    "ar": "معلومات الموديل",
    "en": "Model information"
  },
  {
    "id": "c-1rclke36qcdsz",
    "group": "products",
    "source": "מיון לפי",
    "he": "מיון לפי",
    "ar": "رتب حسب",
    "en": "Sort by"
  },
  {
    "id": "c-13ajsjq7nan7m",
    "group": "products",
    "source": "מפרט",
    "he": "מפרט",
    "ar": "المواصفات",
    "en": "Specification"
  },
  {
    "id": "c-1mknyg5q7poad",
    "group": "products",
    "source": "מפרט טכני",
    "he": "מפרט טכני",
    "ar": "المواصفات الفنية",
    "en": "Technical specifications"
  },
  {
    "id": "c-1b1ai1syxd28o",
    "group": "products",
    "source": "מתכננים נכון, מתקינים בקפידה.",
    "he": "מתכננים נכון, מתקינים בקפידה.",
    "ar": "نخطط بدقة ونركب بعناية.",
    "en": "Thoughtfully planned. Carefully installed."
  },
  {
    "id": "c-1pnat2g1uqiudo",
    "group": "products",
    "source": "נבחרו להשוואה",
    "he": "נבחרו להשוואה",
    "ar": "تم اختيارها للمقارنة",
    "en": "selected to compare"
  },
  {
    "id": "c-nxioqgrhwsms",
    "group": "products",
    "source": "ניקוי השוואה",
    "he": "ניקוי השוואה",
    "ar": "مسح المقارنة",
    "en": "Clear comparison"
  },
  {
    "id": "c-vhty97hrhgv3",
    "group": "products",
    "source": "נסו שם דגם אחר או הרחיבו את הסינון.",
    "he": "נסו שם דגם אחר או הרחיבו את הסינון.",
    "ar": "جرّب اسمًا آخر أو خفف شروط البحث.",
    "en": "Try another model name or broaden your filters."
  },
  {
    "id": "c-13r4cuq1tzk4gy",
    "group": "products",
    "source": "סגירת השוואה",
    "he": "סגירת השוואה",
    "ar": "إغلاق المقارنة",
    "en": "Close comparison"
  },
  {
    "id": "c-8wvk5z1aeotnb",
    "group": "products",
    "source": "סדר מומלץ",
    "he": "סדר מומלץ",
    "ar": "الترتيب المقترح",
    "en": "Featured"
  },
  {
    "id": "c-1idu7wrwzqewb",
    "group": "products",
    "source": "ספרו לנו על החדר. נעזור לכם לבחור את המזגן המתאים.",
    "he": "ספרו לנו על החדר. נעזור לכם לבחור את המזגן המתאים.",
    "ar": "أخبرنا عن الغرفة، وسنساعدك في اختيار المكيف المناسب.",
    "en": "Tell us about your room. We’ll help you find the right model."
  },
  {
    "id": "c-1xfgmxe1kiziv2",
    "group": "products",
    "source": "עוד אפשרויות",
    "he": "עוד אפשרויות",
    "ar": "خيارات أخرى",
    "en": "MORE TO EXPLORE"
  },
  {
    "id": "c-pcxn5cbfdkqw",
    "group": "products",
    "source": "עוד על הדגם",
    "he": "עוד על הדגם",
    "ar": "تفاصيل الموديل",
    "en": "Explore"
  },
  {
    "id": "c-1hx3o77y899pf",
    "group": "products",
    "source": "קטגוריה",
    "he": "קטגוריה",
    "ar": "التصنيف",
    "en": "Category"
  },
  {
    "id": "c-vcfpdrdkbgcr",
    "group": "products",
    "source": "שווה להכיר גם",
    "he": "שווה להכיר גם",
    "ar": "تعرّف أيضًا على",
    "en": "A few more possibilities"
  },
  {
    "id": "c-sl6jvzvo0pgz",
    "group": "products",
    "source": "תמונת אווירה להמחשה, אינה מציגה את הדגם.",
    "he": "תמונת אווירה להמחשה, אינה מציגה את הדגם.",
    "ar": "صورة أجواء للتوضيح، لا تعرض هذا الموديل.",
    "en": "Room inspiration. Does not show this specific model."
  },
  {
    "id": "c-1h5oqub1ihq0g7",
    "group": "products",
    "source": "תמונת אווירה של חלל ממוזג",
    "he": "תמונת אווירה של חלל ממוזג",
    "ar": "صورة أجواء لغرفة مكيفة",
    "en": "Air-conditioned room inspiration"
  },
  {
    "id": "c-8bexi327mmyn",
    "group": "products",
    "source": "תמונת סדרת המוצר. להמחשה בלבד.",
    "he": "תמונת סדרת המוצר. להמחשה בלבד.",
    "ar": "صورة سلسلة المنتج، للتوضيح فقط.",
    "en": "Product series image. For illustration."
  },
  {
    "id": "c-1b7nf7vtb8cjj",
    "group": "products",
    "source": "תפוקת קירור",
    "he": "תפוקת קירור",
    "ar": "قدرة التبريد",
    "en": "Cooling capacity"
  },
  {
    "id": "c-1s5osvs1mpwmrc",
    "group": "services",
    "source": "דואגים למזגן. ולנוחות שלכם.",
    "he": "דואגים למזגן. ולנוחות שלכם.",
    "ar": "نعتني بمكيفك. وبراحتك.",
    "en": "Care for your air. Care for your comfort."
  },
  {
    "id": "c-1pejxw0174xn2c",
    "group": "services",
    "source": "התקנה ושירות",
    "he": "התקנה ושירות",
    "ar": "التركيب والصيانة",
    "en": "INSTALLATION & SERVICE"
  },
  {
    "id": "c-1isn5no1yugwyk",
    "group": "services",
    "source": "התקנה, תחזוקה ותיקונים — עם תשומת לב לפרטים ושיחה בגובה העיניים. שירות לבית ולעסק בכל ערי ישראל.",
    "he": "התקנה, תחזוקה ותיקונים — עם תשומת לב לפרטים ושיחה בגובה העיניים. שירות לבית ולעסק בכל ערי ישראל.",
    "ar": "تركيب وصيانة وإصلاح، باهتمام بالتفاصيل وتواصل واضح. خدمة للبيوت والأعمال في جميع المدن في إسرائيل.",
    "en": "Installation, maintenance and repairs, with attention to detail and straightforward advice. Serving homes and businesses throughout Israel."
  },
  {
    "id": "c-1cue7pqlmdgtu",
    "group": "services",
    "source": "כך חוזרים לאוויר טוב.",
    "he": "כך חוזרים לאוויר טוב.",
    "ar": "هكذا نعيد الهواء الجيد.",
    "en": "Your way back to better air."
  },
  {
    "id": "c-1ysb6dw178fyw",
    "group": "services",
    "source": "לתיאום השירות",
    "he": "לתיאום השירות",
    "ar": "اطلب هذه الخدمة",
    "en": "Arrange this service"
  },
  {
    "id": "c-os3vwz18ppnf3",
    "group": "services",
    "source": "פשוט, מההתחלה",
    "he": "פשוט, מההתחלה",
    "ar": "بوضوح، من البداية",
    "en": "SIMPLE FROM THE START"
  }
] as const;
