import assert from "node:assert/strict";
import { mkdirSync } from "node:fs";
import { chromium } from "@playwright/test";
import { selectByValue } from "./select-helper.mjs";

const baseUrl = new URL(process.env.SITE_TEST_BASE_URL ?? "http://127.0.0.1:3000");
const username = process.env.ADMIN_USERNAME;
const password = process.env.ADMIN_PASSWORD;
if (!username || !password) throw new Error("Set ADMIN_USERNAME and ADMIN_PASSWORD for the CMS QA run.");

async function saveCmsChanges(page, label) {
  const pending = page.waitForResponse((response) =>
    response.url().includes("/api/admin/content") && response.request().method() === "PUT",
  );
  await page.locator(".cms-sticky-save button").click();
  const response = await pending;
  const body = await response.text();
  assert.equal(response.status(), 200, `${label} failed to save: ${body}`);
  await page.locator(".admin-notice.success").waitFor();
  return JSON.parse(body);
}

async function editLocalizedText(field, language, text) {
  await field.locator(`.cms-language-tab[data-language="${language}"]`).click();
  await field.locator(".cms-localized-editor input, .cms-localized-editor textarea").fill(text);
}

const browser = await chromium.launch();
try {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(new URL("/admin", baseUrl).href);
  await selectByValue(page, page.locator(".admin-language .select-field-trigger"), "en");
  await page.getByLabel("Username").fill(username);
  await page.getByLabel("Password").fill(password);
  await page.getByRole("button", { name: "Open admin dashboard" }).click();
  await page.locator(".admin-stat-grid").waitFor();
  await page.locator(".admin-sidebar > button").nth(3).click();
  await page.locator(".cms-root").waitFor();

  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 920 });
    for (const language of ["he", "ar", "en"]) {
      await selectByValue(page, page.locator(".admin-language .select-field-trigger"), language);
      await page.waitForFunction((value) => document.documentElement.lang === value, language);
      const size = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth }));
      assert.ok(size.document <= size.viewport + 2, `CMS overflows at ${width}px in ${language}.`);
      assert.equal(await page.locator(".cms-tabs button").count(), 11, "All content modules should be available in each language.");
    }
  }

  await selectByValue(page, page.locator(".admin-language .select-field-trigger"), "en");
  await page.setViewportSize({ width: 1440, height: 1000 });
  mkdirSync("qa", { recursive: true });
  await page.screenshot({ path: "qa/admin-cms-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "qa/admin-cms-mobile.png", fullPage: false });
  await page.setViewportSize({ width: 1440, height: 1000 });

  const contentUrl = new URL("/api/admin/content", baseUrl).href;
  const original = await (await context.request.get(contentUrl)).json();
  await page.locator(".cms-tabs button").nth(2).click();
  const firstProduct = page.locator(".cms-list > .cms-entity").first();
  await firstProduct.locator(":scope > .cms-entity-title").click();
  const initialPrice = original.products[0].price;
  await firstProduct.getByLabel("Price ₪", { exact: true }).fill(String(initialPrice + 7));
  await page.locator(".cms-sticky-save button").click();
  await page.locator(".admin-notice.success").waitFor();
  let saved = await (await context.request.get(contentUrl)).json();
  assert.equal(saved.products[0].price, initialPrice + 7, "CMS product price should persist.");
  await page.goto(new URL(`/products/${original.products[0].id}`, baseUrl).href);
  await page.waitForFunction((price) => document.querySelector(".detail-price strong")?.textContent?.replace(/\D/g, "") === String(price), initialPrice + 7);
  await page.goto(new URL("/admin", baseUrl).href);
  await page.locator(".admin-stat-grid").waitFor();
  await page.locator(".admin-sidebar > button").nth(3).click();
  await page.locator(".cms-root").waitFor();

  await page.locator(".cms-tabs button").nth(4).click();
  await selectByValue(page, page.locator(".admin-language .select-field-trigger"), "he");
  const addOfferButton = page.locator(".cms-card .admin-panel-head .admin-primary-button");
  await addOfferButton.click();
  await addOfferButton.click();
  await page.locator(".cms-list > .cms-entity").last().waitFor();
  saved = await saveCmsChanges(page, "Adding two offers in Hebrew");
  assert.equal(saved.offers.length, original.offers.length + 2, "New multilingual offers should persist in Hebrew.");
  assert.equal(new Set(saved.offers.map((item) => item.id)).size, saved.offers.length, "New offers must have unique IDs.");

  await page.locator(".cms-tabs button").nth(1).click();
  const copyEntry = page.locator(".cms-copy-item").first();
  await copyEntry.locator("summary").click();
  const originalArabic = (await context.request.get(contentUrl)).ok() ? saved.copy[0].ar : "";
  const changedArabic = `${originalArabic} · CMS QA`;
  const copyEntryField = copyEntry.locator(".cms-localized");
  await editLocalizedText(copyEntryField, "ar", changedArabic);
  await copyEntryField.locator(".cms-copy-all-languages").click();
  await page.locator(".cms-sticky-save button").click();
  await page.locator(".admin-notice.success").waitFor();
  saved = await (await context.request.get(contentUrl)).json();
  assert.equal(saved.copy[0].ar, changedArabic, "A visitor-facing translation should persist.");
  assert.equal(saved.copy[0].he, changedArabic, "Copy to all languages should copy the active translation.");
  assert.equal(saved.copy[0].en, changedArabic, "Copy to all languages should update every translation.");

  await page.locator(".cms-tabs button").nth(8).click();
  const newTitle = "CMS metadata QA title";
  await editLocalizedText(page.locator(".cms-card").nth(1).locator(".cms-localized").first(), "he", newTitle);
  await page.locator(".cms-sticky-save button").click();
  await page.locator(".admin-notice.success").waitFor();
  await page.goto(new URL("/", baseUrl).href);
  await page.waitForFunction((title) => document.title.includes(title), newTitle);

  await page.goto(new URL("/admin", baseUrl).href);
  await page.locator(".admin-stat-grid").waitFor();
  await page.locator(".admin-sidebar > button").nth(3).click();
  await page.locator(".cms-tabs button").nth(10).click();

  const getSavedContent = async () => (await context.request.get(contentUrl)).json();
  await page.locator(".cms-tabs button").nth(2).click();
  await page.locator(".cms-subtabs button").nth(0).click();
  await selectByValue(page, page.locator(".admin-language .select-field-trigger"), "he");
  let beforeAdds = await getSavedContent();
  const addProductButton = page.locator(".cms-card .admin-panel-head .admin-primary-button").first();
  await addProductButton.click();
  const quickProduct = page.locator(".cms-product-quick");
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 920 });
    const quickLayout = await page.evaluate(() => ({ viewport: innerWidth, document: document.documentElement.scrollWidth }));
    assert.ok(quickLayout.document <= quickLayout.viewport + 2, `Quick product form overflows at ${width}px.`);
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "qa/admin-product-quick-add.png", fullPage: true });
  const quickName = quickProduct.locator(".cms-product-quick-name .cms-localized");
  await editLocalizedText(quickName, "he", "QA Quick Hebrew");
  await editLocalizedText(quickName, "ar", "QA Quick Model AR");
  await editLocalizedText(quickName, "en", "QA Quick Model EN");
  await quickProduct.locator(".cms-product-quick-grid input[type=number]").nth(0).fill("1490");
  await quickProduct.locator(".cms-product-quick-grid input[type=number]").nth(1).fill("9000");
  await selectByValue(page, quickProduct.locator(".cms-product-quick-image .select-field-trigger"), "/images/tadiran.webp");
  assert.equal(await quickProduct.locator(".cms-product-quick-section").last().locator("label.cms-field select").count(), 0, "A room category should not show a second, duplicate room-size selector.");
  const quickSpecRepeater = quickProduct.locator(".cms-product-quick-specs");
  const quickSpecBulk = quickSpecRepeater.locator(".cms-product-bulk-entry");
  await quickSpecBulk.locator(":scope > summary").click();
  await quickSpecBulk.locator("textarea").fill("QA specification HE | 9,000 BTU\nPower supply | 230 V / 50 Hz");
  await quickSpecBulk.locator(".cms-add-row").click();
  assert.equal(await quickSpecRepeater.locator(".cms-product-data-row").count(), 2, "Pasting a list should create multiple specification rows.");
  await quickSpecRepeater.locator(".cms-copy-all-languages").click();
  const quickSpecRow = quickSpecRepeater.locator(".cms-product-data-row").first();
  await quickSpecRepeater.locator('.cms-language-tab[data-language="ar"]').click();
  assert.equal(await quickSpecRow.locator(".cms-field input").first().inputValue(), "QA specification HE", "Changing the group language should show the selected translation in every row.");
  await quickSpecRow.locator(".cms-field input").first().fill("QA specification AR");
  await quickSpecRepeater.locator('.cms-language-tab[data-language="en"]').click();
  assert.equal(await quickSpecRow.locator(".cms-field input").first().inputValue(), "QA specification HE", "Translations should remain independent when switching the group language.");
  await quickSpecRow.locator(".cms-field input").nth(1).fill("9,100 BTU");
  const quickFeatureRepeater = quickProduct.locator(".cms-product-quick-features");
  const quickFeatureBulk = quickFeatureRepeater.locator(".cms-product-bulk-entry");
  await quickFeatureBulk.locator(":scope > summary").click();
  await quickFeatureBulk.locator("textarea").fill("QA feature HE\nQuiet operation");
  await quickFeatureBulk.locator(".cms-add-row").click();
  assert.equal(await quickFeatureRepeater.locator(".cms-product-data-row").count(), 2, "Pasting a list should create multiple feature rows.");
  await quickFeatureRepeater.locator(".cms-copy-all-languages").click();
  await selectByValue(page, quickProduct.locator(".cms-product-quick-gallery .cms-gallery-add .select-field-trigger"), "/images/electra.webp");
  await editLocalizedText(quickProduct.locator(".cms-product-quick-section").nth(2).locator(".cms-localized").first(), "en", "QA product SEO title");
  await quickProduct.locator(".cms-product-quick-actions .admin-primary-button").click();
  const sourceProductCard = page.locator(".cms-list > .cms-entity").first();
  if (!(await sourceProductCard.evaluate((element) => element.open))) await sourceProductCard.locator(":scope > .cms-entity-title").click();
  assert.equal(await sourceProductCard.locator(".cms-product-core > .cms-localized").count(), 1, "Product names should have one multilingual editor, without a duplicate name field.");
  assert.equal(await sourceProductCard.locator('[data-cms-product-section="translations"]').count(), 0, "The duplicate translations accordion should be removed.");
  await sourceProductCard.locator(".cms-copy-product").click();
  const duplicateQuickProduct = page.locator(".cms-product-quick");
  const duplicateName = duplicateQuickProduct.locator(".cms-product-quick-name .cms-localized");
  await editLocalizedText(duplicateName, "he", "QA Duplicate Hebrew");
  await duplicateName.locator(".cms-copy-all-languages").click();
  await duplicateQuickProduct.locator(".cms-product-quick-grid input[type=number]").nth(0).fill("1590");
  await duplicateQuickProduct.locator(".cms-product-quick-grid input[type=number]").nth(1).fill("9500");
  await duplicateQuickProduct.locator(".cms-product-quick-actions .admin-primary-button").click();
  let afterAdds = await saveCmsChanges(page, "Adding two CMS products in Hebrew");
  assert.equal(afterAdds.products.length, beforeAdds.products.length + 2, "CMS product additions should persist in Hebrew.");
  assert.equal(new Set(afterAdds.products.map((item) => item.id)).size, afterAdds.products.length, "New CMS products must have unique IDs.");
  const addedCmsProducts = afterAdds.products.slice(beforeAdds.products.length);
  assert.equal(addedCmsProducts[0].nameLocalized.he, "QA Quick Hebrew", "Quick product addition should save the Hebrew model name.");
  assert.equal(addedCmsProducts[0].nameLocalized.ar, "QA Quick Model AR", "Quick product addition should save the Arabic model name.");
  assert.equal(addedCmsProducts[0].nameLocalized.en, "QA Quick Model EN", "Quick product addition should save the English model name.");
  assert.equal(addedCmsProducts[0].specs.length, 2, "Quick product addition should save all pasted specification rows.");
  assert.equal(addedCmsProducts[0].specs[0][0], "QA specification HE", "The active-language specification label should be saved.");
  assert.equal(addedCmsProducts[0].specs[0][1], "QA specification AR", "Editing the Arabic tab should save a separate translation.");
  assert.equal(addedCmsProducts[0].specs[0][2], "QA specification HE", "Copying the selected language should populate English.");
  assert.equal(addedCmsProducts[0].specs[0][3], "9,100 BTU", "The shared specification value should be saved.");
  assert.equal(addedCmsProducts[0].features.length, 2, "Quick product addition should save all pasted feature rows.");
  assert.ok(addedCmsProducts[0].gallery.includes("/images/electra.webp"), "Quick product addition should save gallery images.");
  assert.equal(addedCmsProducts[0].seoTitle.en, "QA product SEO title", "Quick product addition should save SEO fields.");
  const duplicateProductCard = page.locator(".cms-list > .cms-entity").nth(beforeAdds.products.length + 1);
  if (!(await duplicateProductCard.evaluate((element) => element.open))) await duplicateProductCard.locator(":scope > .cms-entity-title").click();
  const duplicateAdvanced = duplicateProductCard.locator('[data-cms-product-section="advanced"]');
  await duplicateAdvanced.locator(":scope > summary").click();
  await duplicateAdvanced.locator(".cms-product-id input").fill(addedCmsProducts[0].id);
  const invalidProductSave = page.waitForResponse((response) => response.url().includes("/api/admin/content") && response.request().method() === "PUT");
  await page.locator(".cms-sticky-save button").click();
  const invalidProductResponse = await invalidProductSave;
  assert.equal(invalidProductResponse.status(), 422, "Duplicate product IDs should be rejected.");
  const invalidProductBody = await invalidProductResponse.json();
  const duplicateProductIndex = afterAdds.products.findIndex((item) => item.id === addedCmsProducts[1].id);
  assert.ok(invalidProductBody.issues.some((issue) => issue.path.join(".") === `products.${duplicateProductIndex}.id`), "The duplicate product should be identified by its array position.");
  assert.match(await page.locator(".admin-notice.error").innerText(), /מוצר/, "Hebrew validation should identify the invalid product ID.");
  const repairProductCard = page.locator(".cms-list > .cms-entity").nth(beforeAdds.products.length + 1);
  if (!(await repairProductCard.evaluate((element) => element.open))) await repairProductCard.locator(":scope > .cms-entity-title").click();
  const repairAdvanced = repairProductCard.locator('[data-cms-product-section="advanced"]');
  if (!(await repairAdvanced.evaluate((element) => element.open))) await repairAdvanced.locator(":scope > summary").click();
  await repairAdvanced.locator(".cms-product-id input").fill(`product-cms-qa-${Date.now()}`);
  afterAdds = await saveCmsChanges(page, "Repairing a duplicate product ID");
  assert.equal(new Set(afterAdds.products.map((item) => item.id)).size, afterAdds.products.length, "Product IDs should be unique after repair.");
  const newCmsProduct = afterAdds.products[beforeAdds.products.length];
  assert.ok(newCmsProduct.nameLocalized.he && newCmsProduct.nameLocalized.ar && newCmsProduct.nameLocalized.en, "New CMS products should include all three localized names.");

  const newProductCard = page.locator(".cms-list > .cms-entity").filter({ has: page.locator(`input[value="${newCmsProduct.id}"]`) });
  await newProductCard.waitFor();
  if (!(await newProductCard.evaluate((element) => element.open))) await newProductCard.locator(":scope > .cms-entity-title").click();
  const newProductAdvanced = newProductCard.locator('[data-cms-product-section="advanced"]');
  if (!(await newProductAdvanced.evaluate((element) => element.open))) await newProductAdvanced.locator(":scope > summary").click();
  const specRepeater = newProductAdvanced.locator(".cms-product-specs");
  await specRepeater.locator(".cms-product-row-editor > .cms-add-row").click();
  const specFields = specRepeater.locator(".cms-product-data-row").last().locator("input");
  await specFields.nth(0).fill("QA specification HE");
  await specFields.nth(1).fill("QA specification value");
  await specRepeater.locator(".cms-copy-all-languages").last().click();
  const featureRepeater = newProductAdvanced.locator(".cms-product-features");
  await featureRepeater.locator(".cms-product-row-editor > .cms-add-row").click();
  const featureFields = featureRepeater.locator(".cms-product-data-row").last().locator("input");
  await featureFields.nth(0).fill("QA feature HE");
  await featureRepeater.locator(".cms-copy-all-languages").last().click();
  afterAdds = await saveCmsChanges(page, "Adding product specification and feature rows");
  const savedCmsProduct = afterAdds.products.find((item) => item.id === newCmsProduct.id);
  assert.equal(savedCmsProduct.specs.length, 3, "Product specification rows should persist both during quick add and later editing.");
  assert.equal(savedCmsProduct.features.length, 3, "Product feature rows should persist both during quick add and later editing.");

  await page.locator(".cms-subtabs button").nth(1).click();
  beforeAdds = await getSavedContent();
  const addCategoryButton = page.locator(".cms-card .admin-panel-head .admin-primary-button").first();
  await addCategoryButton.click();
  await addCategoryButton.click();
  afterAdds = await saveCmsChanges(page, "Adding two categories in Hebrew");
  assert.equal(afterAdds.categories.length, beforeAdds.categories.length + 2, "Category additions should persist in Hebrew.");
  const addedCategories = afterAdds.categories.slice(beforeAdds.categories.length);
  assert.notEqual(addedCategories[0].id, addedCategories[1].id, "New categories need unique IDs.");
  const duplicateCategoryCard = page.locator(".cms-list > .cms-entity").filter({ has: page.locator(`input[value="${addedCategories[1].id}"]`) });
  if (!(await duplicateCategoryCard.evaluate((element) => element.open))) await duplicateCategoryCard.locator("summary").click();
  await duplicateCategoryCard.locator(".cms-entity-body .cms-field input").first().fill(addedCategories[0].id);
  const invalidCategorySave = page.waitForResponse((response) => response.url().includes("/api/admin/content") && response.request().method() === "PUT");
  await page.locator(".cms-sticky-save button").click();
  const invalidCategoryResponse = await invalidCategorySave;
  assert.equal(invalidCategoryResponse.status(), 200, "The CMS should repair duplicate category IDs while saving.");
  afterAdds = await getSavedContent();
  assert.equal(new Set(afterAdds.categories.map((item) => item.id)).size, afterAdds.categories.length, "Category IDs should be unique after automatic repair.");
  assert.ok(afterAdds.products.every((product) => afterAdds.categories.some((item) => item.id === product.categoryId)), "Repairing category IDs should preserve product links.");

  await page.locator(".cms-subtabs button").nth(2).click();
  beforeAdds = await getSavedContent();
  const addBrandButton = page.locator(".cms-card .admin-panel-head .admin-primary-button").first();
  await addBrandButton.click();
  await addBrandButton.click();
  afterAdds = await saveCmsChanges(page, "Adding two brands in Hebrew");
  assert.equal(afterAdds.brands.length, beforeAdds.brands.length + 2, "Brand additions should persist in Hebrew.");
  const addedBrands = afterAdds.brands.slice(beforeAdds.brands.length);
  assert.notEqual(addedBrands[0].id, addedBrands[1].id, "New brands need unique stable IDs.");
  const duplicateBrandCard = page.locator(".cms-list > .cms-entity").filter({ has: page.locator(`input[value="${addedBrands[1].id}"]`) });
  if (!(await duplicateBrandCard.evaluate((element) => element.open))) await duplicateBrandCard.locator("summary").click();
  await duplicateBrandCard.locator(".cms-entity-body .cms-field input").first().fill(addedBrands[0].id);
  const invalidBrandSave = page.waitForResponse((response) => response.url().includes("/api/admin/content") && response.request().method() === "PUT");
  await page.locator(".cms-sticky-save button").click();
  const invalidBrandResponse = await invalidBrandSave;
  assert.equal(invalidBrandResponse.status(), 200, "The CMS should repair duplicate brand IDs while saving.");
  afterAdds = await getSavedContent();
  assert.equal(new Set(afterAdds.brands.map((item) => item.id)).size, afterAdds.brands.length, "Brand IDs should be unique after automatic repair.");
  assert.ok(afterAdds.products.every((product) => afterAdds.brands.some((item) => item.id === product.brandId)), "Repairing brand IDs should preserve product links.");

  await page.locator(".cms-tabs button").nth(3).click();
  beforeAdds = await getSavedContent();
  const addServiceButton = page.locator(".cms-card .admin-panel-head .admin-primary-button").first();
  await addServiceButton.click();
  await addServiceButton.click();
  afterAdds = await saveCmsChanges(page, "Adding two services in Hebrew");
  assert.equal(afterAdds.services.length, beforeAdds.services.length + 2, "Service additions should persist in Hebrew.");
  const addedServices = afterAdds.services.slice(beforeAdds.services.length);
  assert.notEqual(addedServices[0].id, addedServices[1].id, "New services need unique IDs.");
  const duplicateServiceCard = page.locator(".cms-list > .cms-entity").filter({ has: page.locator(`input[value="${addedServices[1].id}"]`) });
  if (!(await duplicateServiceCard.evaluate((element) => element.open))) await duplicateServiceCard.locator("summary").click();
  await duplicateServiceCard.locator(".cms-entity-body .cms-field input").first().fill(addedServices[0].id);
  const invalidServiceSave = page.waitForResponse((response) => response.url().includes("/api/admin/content") && response.request().method() === "PUT");
  await page.locator(".cms-sticky-save button").click();
  const invalidServiceResponse = await invalidServiceSave;
  assert.equal(invalidServiceResponse.status(), 422, "Duplicate service IDs should be rejected.");
  const invalidServiceBody = await invalidServiceResponse.json();
  const duplicateServiceIndex = afterAdds.services.findIndex((item) => item.id === addedServices[1].id);
  assert.ok(invalidServiceBody.issues.some((issue) => issue.path.join(".") === `services.${duplicateServiceIndex}.id`), "The duplicate service should be identified by its array position.");
  const repairServiceCard = page.locator(".cms-list > .cms-entity").filter({ has: page.locator(`input[value="${addedServices[0].id}"]`) }).nth(1);
  await repairServiceCard.locator(".cms-entity-body .cms-field input").first().fill(`service-cms-qa-${Date.now()}`);
  afterAdds = await saveCmsChanges(page, "Repairing a duplicate service ID");
  assert.equal(new Set(afterAdds.services.map((item) => item.id)).size, afterAdds.services.length, "Service IDs should be unique after repair.");
  const addedService = afterAdds.services[beforeAdds.services.length];
  const addedServiceCard = page.locator(".cms-list > .cms-entity").filter({ has: page.locator(`input[value="${addedService.id}"]`) });
  if (!(await addedServiceCard.evaluate((element) => element.open))) await addedServiceCard.locator("summary").click();
  await addedServiceCard.locator(".cms-repeater .cms-add-row").click();
  afterAdds = await saveCmsChanges(page, "Adding a service detail");
  assert.equal(afterAdds.services.find((item) => item.id === addedService.id).points.length, 1, "A service detail should persist.");
  beforeAdds = await getSavedContent();
  const addProcessButton = page.locator(".cms-card").nth(1).locator(".cms-add-row");
  await addProcessButton.click();
  await addProcessButton.click();
  afterAdds = await saveCmsChanges(page, "Adding two service process steps");
  assert.equal(afterAdds.servicePage.process.length, beforeAdds.servicePage.process.length + 2, "Service process steps should persist.");
  assert.equal(new Set(afterAdds.servicePage.process.map((item) => item.id)).size, afterAdds.servicePage.process.length, "Service process steps need unique IDs.");

  await page.locator(".cms-tabs button").nth(5).click();
  beforeAdds = await getSavedContent();
  const aboutAddButton = page.locator(".cms-card .admin-panel-head .admin-primary-button").first();
  await aboutAddButton.click();
  await aboutAddButton.click();
  afterAdds = await saveCmsChanges(page, "Adding two about values in Hebrew");
  assert.equal(afterAdds.about.values.length, beforeAdds.about.values.length + 2, "About value additions should persist.");
  assert.equal(new Set(afterAdds.about.values.map((item) => item.id)).size, afterAdds.about.values.length, "About values need unique IDs.");

  await page.locator(".cms-tabs button").nth(6).click();
  beforeAdds = await getSavedContent();
  const faqAndPolicyAddButtons = page.locator(".cms-card .admin-panel-head .admin-primary-button");
  await faqAndPolicyAddButtons.nth(0).click();
  await faqAndPolicyAddButtons.nth(0).click();
  await faqAndPolicyAddButtons.nth(1).click();
  await faqAndPolicyAddButtons.nth(1).click();
  afterAdds = await saveCmsChanges(page, "Adding an FAQ and a policy");
  assert.equal(afterAdds.faqs.length, beforeAdds.faqs.length + 2, "FAQ additions should persist.");
  assert.equal(afterAdds.policies.items.length, beforeAdds.policies.items.length + 2, "Policy additions should persist.");
  assert.equal(new Set(afterAdds.faqs.map((item) => item.id)).size, afterAdds.faqs.length, "FAQ items need unique IDs.");
  assert.equal(new Set(afterAdds.policies.items.map((item) => item.id)).size, afterAdds.policies.items.length, "Policy items need unique IDs.");

  await page.locator(".cms-tabs button").nth(7).click();
  beforeAdds = await getSavedContent();
  const linkAddButtons = page.locator(".cms-add-row");
  assert.equal(await linkAddButtons.count(), 3, "Navigation, footer and social link additions should all be available.");
  await linkAddButtons.nth(0).click();
  await linkAddButtons.nth(0).click();
  await linkAddButtons.nth(1).click();
  await linkAddButtons.nth(1).click();
  await linkAddButtons.nth(2).click();
  await linkAddButtons.nth(2).click();
  afterAdds = await saveCmsChanges(page, "Adding navigation, footer and social links");
  assert.equal(afterAdds.navigation.length, beforeAdds.navigation.length + 2, "Navigation link additions should persist.");
  assert.equal(afterAdds.footer.links.length, beforeAdds.footer.links.length + 2, "Footer link additions should persist.");
  assert.equal(afterAdds.settings.socialLinks.length, beforeAdds.settings.socialLinks.length + 2, "Social link additions should persist.");
  assert.equal(new Set(afterAdds.navigation.map((item) => item.id)).size, afterAdds.navigation.length, "Navigation links need unique IDs.");
  assert.equal(new Set(afterAdds.footer.links.map((item) => item.id)).size, afterAdds.footer.links.length, "Footer links need unique IDs.");
  assert.equal(new Set(afterAdds.settings.socialLinks.map((item) => item.id)).size, afterAdds.settings.socialLinks.length, "Social links need unique IDs.");

  await page.locator(".cms-tabs button").nth(10).click();
  const upload = page.waitForResponse((response) => response.url().includes("/api/admin/media") && response.request().method() === "POST");
  await page.locator(".cms-upload-large input[type=file]").setInputFiles("public/images/hero.webp");
  const uploadResponse = await upload;
  assert.equal(uploadResponse.status(), 200, "CMS media upload should succeed.");
  const uploaded = await uploadResponse.json();
  const mediaCard = page.locator(".cms-media-card").filter({ has: page.locator(`img[src="${uploaded.image}"]`) });
  await mediaCard.waitFor();
  page.on("dialog", (dialog) => dialog.accept());
  await mediaCard.locator("button.cms-delete").click();
  await mediaCard.waitFor({ state: "detached" });

  const usedUpload = page.waitForResponse((response) => response.url().includes("/api/admin/media") && response.request().method() === "POST");
  await page.locator(".cms-upload-large input[type=file]").setInputFiles("public/images/hero.webp");
  const usedUploadResponse = await usedUpload;
  assert.equal(usedUploadResponse.status(), 200, "A second CMS media upload should succeed.");
  const usedImage = (await usedUploadResponse.json()).image;
  await page.locator(".cms-tabs button").nth(2).click();
  await page.locator(".cms-subtabs button").nth(0).click();
  const galleryProduct = page.locator(".cms-list > .cms-entity").filter({ has: page.locator(`input[value="${original.products[0].id}"]`) });
  if (!(await galleryProduct.evaluate((element) => element.open))) await galleryProduct.locator(":scope > .cms-entity-title").click();
  const galleryProductAdvanced = galleryProduct.locator('[data-cms-product-section="advanced"]');
  if (!(await galleryProductAdvanced.evaluate((element) => element.open))) await galleryProductAdvanced.locator(":scope > summary").click();
  await selectByValue(page, page.locator(".cms-gallery-add .select-field-trigger").first(), usedImage);
  await page.locator(".cms-sticky-save button").click();
  await page.locator(".admin-notice.success").waitFor();
  saved = await (await context.request.get(contentUrl)).json();
  assert.ok(saved.products.find((product) => product.id === original.products[0].id).gallery.includes(usedImage), "Product gallery edits should persist from the CMS.");
  await page.goto(new URL(`/products/${original.products[0].id}`, baseUrl).href);
  const galleryChoice = page.locator(".gallery-options button").filter({ has: page.locator(`img[src="${usedImage}"]`) });
  await galleryChoice.waitFor();
  await galleryChoice.click();
  await page.waitForFunction((image) => document.querySelector(".detail-visual > img")?.getAttribute("src") === image, usedImage);
  await page.goto(new URL("/admin", baseUrl).href);
  await page.locator(".admin-stat-grid").waitFor();
  await page.locator(".admin-sidebar > button").nth(3).click();
  await page.locator(".cms-tabs button").nth(10).click();
  await page.locator(".cms-tabs button").nth(7).click();
  await selectByValue(page, page.getByLabel("Company logo"), usedImage);
  await page.locator(".cms-sticky-save button").click();
  await page.locator(".admin-notice.success").waitFor();
  await page.locator(".cms-tabs button").nth(10).click();
  const usedMediaCard = page.locator(".cms-media-card").filter({ has: page.locator(`img[src="${usedImage}"]`) });
  await usedMediaCard.waitFor();
  assert.equal(await usedMediaCard.locator("button.cms-delete").isDisabled(), true, "The CMS should disable deletion for images used by saved content.");
  const guardedDelete = await context.request.delete(new URL("/api/admin/media", baseUrl).href, { data: { image: usedImage } });
  assert.equal(guardedDelete.status(), 409, "The media API should protect images referenced by saved content.");
  const publicContent = await (await context.request.get(new URL("/api/content", baseUrl).href)).json();
  assert.equal(publicContent.settings.logoImage, usedImage, "A selected CMS logo should appear in public site content.");
  assert.equal(publicContent.copy[0].source, undefined, "Public visitors should not receive CMS editor metadata.");
  assert.equal(publicContent.settings.phoneDisplay, saved.settings.phoneDisplay, "Public site content should match persisted admin data.");

  await page.locator(".admin-sidebar-bottom > button").click();
  await page.locator(".admin-auth-card").waitFor();
  const anonymous = await context.request.get(contentUrl);
  assert.equal(anonymous.status(), 401, "Admin content should remain protected after logout.");
  await context.close();
  console.log("CMS QA passed: multilingual layout, product catalog and add buttons, all content groups, service process, gallery/media, SEO and protected session.");
} finally {
  await browser.close();
}
